name: Test github action enviroment

on:
  workflow_dispatch: 

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Dump installed packages
        run: dpkg -l --no-pager
      - name: Dump env
        run: /usr/bin/env
      - name: test cosign
        run: cosign version
  windows:
    runs-on: windows-latest
    steps:
      - name: Dump env
        shell: pwsh
        run: |
          Get-ChildItem Env: | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Value)" }
      - name: test cosign
        run: cosign version